{
  pkgs,
  ...
}:
let
  myvars = import ../../../vars;
in
{
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  users.users = {
    "${myvars.userName}" = {
      # generated by `mkpasswd -m scrypt`
      # we have to use initialHashedPassword here when using tmpfs for /
      inherit (myvars) initialHashedPassword;
      openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
      home = "/home/${myvars.userName}";
      isNormalUser = true;
      shell = pkgs.fish;
      extraGroups = [
        "wheel"
        "users"
        "networkmanager"
      ];
    };
  };

  # root's ssh key are mainly used for remote deployment
  users.users.root = {
    initialHashedPassword = myvars.initialHashedPassword;
    openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
  };

  programs.fish.enable = true;
}
