keys:
  - &server age1vykkyvxznc7trcxcaz7qnel263te6fg96ux2cnqaqhqh32fw030qzyq8cp
  - &macbook age17qcah87kmqh57txu9xjzaglshv4nuwm32pgs0ydvy9vjk0s9f4mqcp26fy

creation_rules:
  - path_regex: secrets/*
    key_groups:
      - age:
          - *server
          - *macbook

  - path_regex: modules/*
    key_groups:
      - age:
          - *server
          - *macbook
