{
  userName = "aaron";
  fullName = "Aaron";
  timeZone = "Asia/Singapore";
  stateVersion = "25.05";

  gitEmail = "the.sad@niceboy.org";

  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....mTYw28fnKaMzRRszVZhR21$tYH1/Z7DDGft7oGc67h61EBTXZ6JXbuzHJNIYmvYhV1";

  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKHjMAQUXfyMv8TG1NfqjmQJG3gqZkh25KAvAMvxVrWS Aaron@MacBook-Pro"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA6xNNhF6jaPKuch8vSHwHTGlbyn4i2zSHxrqGOiacxG Aaron@Deployment"
  ];
}
