{
  config,
  pkgs,
  lib,
  myvars,
  ...
}:
{
  users.mutableUsers = false;

  users.groups = {
    "${myvars.userName}" = { };
    docker = { };
  };

  users.users = {
    "${myvars.userName}" = {
      # generated by `mkpasswd -m scrypt`
      # we have to use initialHashedPassword here when using tmpfs for /
      inherit (myvars) initialHashedPassword;
      openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
      home = "/home/${myvars.userName}";
      isNormalUser = true;
      shell = pkgs.zsh;
      extraGroups = [
        myvars.userName
        "users"
        "networkmanager"
        "wheel"
        "docker"
      ];
    };
    # root's ssh key are mainly used for remote deployment
    root = {
      initialHashedPassword = myvars.initialHashedPassword;
      openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
    };
  };

  security.sudo.extraRules = [
    {
      users = [ "${myvars.userName}" ];
      commands = [
        {
          command = "/run/current-system/sw/bin/nix";
          options = [ "NOPASSWD" ];
        }
        {
          command = "/run/current-system/sw/bin/nixos-rebuild";
          options = [ "NOPASSWD" ];
        }
        {
          command = "/run/current-system/sw/bin/nix-collect-garbage";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  environment.pathsToLink = [ "/share/zsh" ];
}
