{
  config,
  lib,
  pkgs,
  myvars,
  ...
}: {
  imports = [
    ./zram.nix
    ./hardware.nix
    ./impermanence.nix
  ];

  networking.hostName = "mechrevo";
  networking.networkmanager.enable = true;

  time.timeZone = "${myvars.defaultTimeZone}";

  i18n.defaultLocale = "en_US.UTF-8";

  services.openssh = {
    enable = true;
    ports = [233];
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
    openFirewall = true;
  };

  users.mutableUsers = false;

  users.users = {
    "${myvars.userName}" = {
      # generated by `mkpasswd -m scrypt`
      # we have to use initialHashedPassword here when using tmpfs for /
      inherit (myvars) initialHashedPassword;
      openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
      home = "/home/${myvars.userName}";
      isNormalUser = true;
      extraGroups = [
        myvars.userName
        "users"
        "networkmanager"
        "wheel"
        "docker"
        "libvirtd"
      ];
    };
    # root's ssh key are mainly used for remote deployment
    root = {
      initialHashedPassword = myvars.initialHashedPassword;
      openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
    };
  };

  system.stateVersion = "${myvars.stateVersion}";
}
